# Generated by Django 4.1.2 on 2022-10-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='text_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('language', models.CharField(max_length=34, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'тексты',
            },
        ),
    ]
